SERVER_PORT = 8080
SERVER_HTTPS_PORT = 8443
SERVER_HOST = "localhost"
SERVER_BIND_HOST = "0.0.0.0"

ktor {
  deployment {
    host = ${SERVER_BIND_HOST}
    port = ${SERVER_PORT}
    sslPort = ${SERVER_HTTPS_PORT}
    watch = [ classes ]
  }

  security {
    ssl {
      keyStore = "ssl/server-keystore.p12"
      keyAlias = "server"
      keyStorePassword = "changeit"
      privateKeyPassword = "changeit"
    }
  }
}

database {
  url = "jdbc:postgresql://localhost:5432/project_manager"
  driver = "org.postgresql.Driver"
  user = "pm_user"
  password = "pm_password"
  maximumPoolSize = 5
}
