SERVER_PORT = 8080

ktor {
  deployment {
    port = ${SERVER_PORT}
    watch = [ classes ]
  }
  application {
    modules = [ hu.akosholloszabo.project_manager.project_manager_workshop.ApplicationKt.module ]
  }
}

database {
  url = "jdbc:postgresql://localhost:5432/project_manager"
  driver = "org.postgresql.Driver"
  user = "pm_user"
  password = "pm_password"
  maximumPoolSize = 5
}
