storage.backend=ENCRYPTED
project_manager.serverKeystorePassword=changeit
cipher.encryption_algorithm=AES/GCM/NoPadding
cipher.message_digest_algorithm=SHA-256
cipher.key_speed=project-manager workshop 2025
cipher.iv_size=12
cipher.key_algorithm=AES

